development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pescapp_development
  user: oferusdev
  password: oferusdev

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pescapp_test
  user: oferusdev
  password: oferusdev

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: 5